### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by oSerenity** [spikespaz/search-deflector#114]
> **IMPORTANT:** READ EVERYTHING!!! That includes the wiki. Make sure you've skimmed the wiki before making a bug report.
> https://github.com/spikespaz/search-deflector/wiki
>
> This issue should be properly formatted in markdown. If you don't know what that is, read the following website before continuing:
> https://guides.github.com/features/mastering-markdown/
>
> Most of the text in this issue should be replaced with your own or deleted. Do not delete section headers unless the information they would contain is irrelevant or inapplicable.

## Bug Description

If you have any other details, replace this line, otherwise delete it.

**File:** `source\deflector.d`

**Line:** 53

**Message:**

```
There was an error deflecting your search. Passed URI is:	microsoft-edge:https://go.microsoft.com/fwlink/?LinkId=528882
```

## How to Reproduce

**Query string:**
```

```

**Query or URL:**
```

```

**Steps to reproduce the behavior:**

## Environmental Details

**Browser**: Opera Stable

**Search Engine:** UNKNOWN STRING

**Custom browser path:**
```
C:\Users\serenity\AppData\Local\Programs\Opera\Launcher.exe
```

**Custom search engine URL:**
```
google.com/search?q={{query}}
```

| Windows Version | `1909` |
| --- | --- |
| Build Number | `18363` |
| Edition | `Core` |
| Insiders Preview |  |

**Comment by spikespaz** [comment]
Don't select the Opera Launcher. Select the actual browser executable instead.

**Comment by oSerenity** [comment]
> Don't select the Opera Launcher. Select the actual browser executable instead.

i suggest adding a warning if you can make them go to the browser location and select the version folder and click opera instead of browser to avoid this issue in the future thanks for the help...
