### ISSUE TITLE
I can't find info on how to install this!  I have zip file. What is the installer?

### ISSUE THREAD

**Issue by susan-see** [spikespaz/search-deflector#132]
I downloaded the zip file and extracted.
The readme.md file says to look at the "Setup & Installing" info at a link. The link lands me here
https://github.com/spikespaz/search-deflector/wiki/ showing a Table of Contents.
None of these links work anymore. 
This doesn't exist anymore according to this issue & replies. from June 4, 2020. 
Spikespaz says "The new installer should be sufficiently intelligible to new users." I do not know what "the new installer" is. The zip file doesn't contain an installer that I recognize. How do I install it? Thank you!

**Comment by spikespaz** [comment]
https://github.com/spikespaz/search-deflector/releases

Download the latest installer from there and click through it like any other software. Additionally there's a table of links in the readme, the releases page and a short link to the latest download are present.
