### ISSUE TITLE
Search Deflector detected as Malware (Malware.AI)?

### ISSUE THREAD

**Issue by Uberck** [spikespaz/search-deflector#154]
Search Deflector has been marked as Malware.AI.1903978565 by Malwarebytes. Is there something going on with the program or is this just a false positive? They do mention @ https://blog.malwarebytes.com/detections/malware-ai/ that the detection is completely autonomous so I don't put it past that being a possibility. Any insight would be greatly appreciated. Is this program still safe?

Here is a link to some screenshots of the file information and Malwarebytes results:
https://1drv.ms/u/s!AhIl37lJZXXm_Fsw__PSkm26SjkH?e=znyMwy

Please don't hesitate to let me know if anymore info is needed from my end.

Here is the output from Malwarebytes (also in the linked zip file):

****************************************************************************************************************

Malwarebytes
www.malwarebytes.com

-Log Details-
Scan Date: 5/21/21
Scan Time: 2:52 AM
Log File: 197b8740-ba01-11eb-84d2-40a8f068fa11.json

-Software Information-
Version: 4.3.0.98
Components Version: 1.0.1292
Update Package Version: 1.0.40722
License: Premium

-System Information-
OS: Windows 10 (Build 19042.985)
CPU: x64
File System: NTFS
User: System

-Scan Summary-
Scan Type: Threat Scan
Scan Initiated By: Scheduler
Result: Completed
Objects Scanned: 574757
Threats Detected: 1
Threats Quarantined: 0
Time Elapsed: 16 min, 5 sec

-Scan Options-
Memory: Enabled
Startup: Enabled
Filesystem: Enabled
Archives: Enabled
Rootkits: Disabled
Heuristics: Enabled
PUP: Detect
PUM: Detect

-Scan Details-
Process: 0
(No malicious items detected)

Module: 0
(No malicious items detected)

Registry Key: 0
(No malicious items detected)

Registry Value: 0
(No malicious items detected)

Registry Data: 0
(No malicious items detected)

Data Stream: 0
(No malicious items detected)

Folder: 0
(No malicious items detected)

File: 1
Malware.AI.1903978565, C:\PROGRAM FILES (X86)\SEARCH DEFLECTOR\DEFLECTOR.EXE, No Action By User, 1000000, 0, 1.0.40722, 4811A2F79A77BEEA717C6845, dds, 01254447, E49E5827096F269E0A2E9FC167E52E6F, C2397EB8066BDD30463BD409D9F7775E9DAB2AEF3BE3796B47FC87718C08CB99

Physical Sector: 0
(No malicious items detected)

WMI: 0
(No malicious items detected)

(end)

**Comment by spikespaz** [comment]
This has been addressed in previous issues and an entry added on the Wiki for any users receiving false-positives. Malwarebytes is a good antivirus but every antivirus can be wrong.

https://github.com/spikespaz/search-deflector/wiki/Troubleshooting#blocked-by-antivirus
