### ISSUE TITLE
Unable to "Continue on PC" when sharing via Android.

### ISSUE THREAD

**Issue by fvknl** [spikespaz/search-deflector#20]
Hi Dev,

Loving the app, much more flexible than Edge Deflector, an issue I encountered on Edge Deflector was the same as this, not being able to use the Continue on PC sharing feature on Android when your phone is linked.

Currently on Insider Build 17754.

Cheers.

**Comment by spikespaz** [comment]
I am unaware of this feature. What is "Continue on PC"?

**Comment by fvknl** [comment]
It's not that important. Get sleep, lol. Plenty of time.

**Comment by spikespaz** [comment]
Well I don't know. This is actually pretty cool lol, I just tried it out and it works for me. What version are you using? What did you select for your config options? Try running the force update in your start menu apps list.

There is a section on [this Wiki page](https://github.com/spikespaz/search-deflector/wiki/Troubleshooting) that describes how to do that.

If it still doesn't work for you send me the link of the site that doesn't work.

**Comment by fvknl** [comment]
Will do, I have to head out now so I’ll attempt these troubleshooting steps when I get home. I wonder if they’ve changed something in the new insider build that kills it. What windows 10 OS version are you running?

And yeah, it’s pretty handy. At nights when I am in bed and find something interesting I want to read I just send it to my PC for the morning.





Sent from Mail for Windows 10

**Comment by spikespaz** [comment]
Running 17744. On slow lane, maybe they changed something in your version. Thanks for reporting this.

**Comment by spikespaz** [comment]
Did you have a change to try those suggestions?

**Comment by fvknl** [comment]
Shit, forgot to reply. I did to no avail. HOWEVER, I unlinked and relinked my phone in my Microsoft account and it started working. Lol.

Just want to express my gratitude for your help and for your work on such a great app. Kudos!


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by spikespaz** [comment]
If you have any more problems just reopen this issue.
Glad it works for you. If you wouldn't mind, could you please star the repository? 80 stars is a great milestone for me.

Thanks!
