### ISSUE TITLE
Is it just me or the Web Results are still in Bing?

### ISSUE THREAD

**Issue by anton31kah** [spikespaz/search-deflector#23]
I mean clicking enter does search the search engine I chose in the browser I chose but the results accessed from clicking right or on the button '>' next to the item, it shows results in Bing, here is what I mean

![Image](https://i.imgur.com/7g2PnMD.jpg)

**Comment by spikespaz** [comment]
There is no way to change the search engine shown in the right panel of the start menu. I can only change what happens after you press Enter.

If I figure out a way to do this in the future I certainly will implement it, but I can't change the system user interface.

**Comment by spikespaz** [comment]
I will also add this to the Troubleshooting page of the Wiki. Thanks.
