### ISSUE TITLE
Error on Windows 11

### ISSUE THREAD

**Issue by Justin1904** [spikespaz/search-deflector#244]
> **IMPORTANT:** READ EVERYTHING!!! That includes the wiki. Make sure you've skimmed the wiki before making a bug report.
> https://github.com/spikespaz/search-deflector/wiki
>
> This issue should be properly formatted in markdown. If you don't know what that is, read the following website before continuing:
> https://guides.github.com/features/mastering-markdown/
>
> Most of the text in this issue should be replaced with your own or deleted. Do not delete section headers unless the information they would contain is irrelevant or inapplicable.

## Bug Description

I am using search deflector on Windows 11. After running the configure.exe to set my preferences, I ran the deflector.exe to launch the program and hit an error.

**File:** `source\deflector.d`

**Line:** 19

**Message:**

```
Expected one URI argument, recieved: 
["C:\\Program Files (x86)\\Search Deflector\\deflector.exe"]
```

## How to Reproduce

**Query string:**
```

```

**Query or URL:**
```

```

**Steps to reproduce the behavior:**

## Environmental Details

**Browser**: Microsoft Edge

**Search Engine:** UNKNOWN STRING

**Custom browser path:**
```
C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe
```

**Custom search engine URL:**
```
google.com/search?q={{query}}
```

| Windows Version | `2009` |
| --- | --- |
| Build Number | `22000` |
| Edition | `Enterprise` |
| Insiders Preview |  |

**Comment by spikespaz** [comment]
You're not supposed to start `deflector.exe` manually. It needs information that the system passes, and when you launch it manually, it do something with nothing.
