### ISSUE TITLE
404 page not found when wanting to download

### ISSUE THREAD

**Issue by HannoVB1** [spikespaz/search-deflector#246]
When going to [https://birkett.dev/tools/repo-dl/?user=spikespaz&repo=search-deflector&file=SearchDeflector-Installer.exe](https://birkett.dev/tools/repo-dl/?user=spikespaz&repo=search-deflector&file=SearchDeflector-Installer.exe) you get a 404 page not found error

## Expected Behavior

Start of a download, or a page where you can download the latest version

## Screenshots

![image](https://user-images.githubusercontent.com/98668034/155889703-307b6526-f7d6-401e-90a4-81704d5b7c50.png)

**Comment by HannoVB1** [comment]
Forgot to mention that you get brought to this link from here:
![image](https://user-images.githubusercontent.com/98668034/155889795-07d1059d-2587-4c11-89a2-aa4871d7d671.png)

in the readme section.

**Comment by spikespaz** [comment]
Deleted a repository forgetting it had a `gh-pages` branch. All good now.
