### ISSUE TITLE
Search Deflector crashed on opening a link from the start menu search

### ISSUE THREAD

**Issue by computeteen5** [spikespaz/search-deflector#25]
I have encountered an error launching Search Deflector.
The error information follows below.

**File:** `std\process.d`

**Line:** 752

**Message:**
```
Failed to spawn new process (The system cannot find the file specified.)
```

**Stack Trace:**
```
0x00007FF694F0B64D
0x00007FF694F0B3A6
0x00007FF694F0425C
0x00007FF694EF107C
0x00007FF694ECD8C3
0x00007FF694ECD2A2
0x00007FF694ECDAD7
0x00007FF694EC150F
0x00007FF694EF728D
0x00007FF694EF713A
0x00007FF694F15BD0
0x00007FFF271D7E94 in BaseThreadInitThunk
0x00007FFF28657AD1 in RtlUserThreadStart

```

**Comment by spikespaz** [comment]
Open "Search Deflector/Configure" in your start meny apps list. Copy the line that has the name and path of the browser you selected, and paste it here.

If you used a custom path  you typed it in wrong.

**Comment by spikespaz** [comment]
Any update on this?

**Comment by computeteen5** [comment]
After I reconfigured the program and set it to use Google Chrome everything was fine. I had uninstalled Opera and it was still pointing to it. Perhaps add a sanity check for the custom app being uninstalled?

**Comment by spikespaz** [comment]
I'm concerned about overhead, but I'll implement it anyway.

![image](https://user-images.githubusercontent.com/12502988/45847407-cdb94480-bcdf-11e8-82d8-58b34eaa4046.png)
