### ISSUE TITLE
Search engine didn't set properly

### ISSUE THREAD

**Issue by readyact** [spikespaz/search-deflector#26]
I have encountered an error launching Search Deflector.
The error information follows below.

**File:** `std\windows\registry.d`

**Line:** 328

**Message:**
```
Failed to create requested key: "SearchDeflector": Access is denied. (error 5)
```

**Stack Trace:**
```
0x00007FF635A1151D
0x00007FF635A11276
0x00007FF635A0A12C
0x00007FF6359F6BCC
0x00007FF6359A988E
0x00007FF6359AB9DB
0x00007FF6359973D5
0x00007FF6359961D5
0x00007FF635995E10
0x00007FF6359FD1DD
0x00007FF6359FD08A
0x00007FF635A1BAA8
0x00007FF96A7F3034 in BaseThreadInitThunk
0x00007FF96BA31461 in RtlUserThreadStart

```

**Comment by spikespaz** [comment]
The installer must be run as administrator.

**Comment by spikespaz** [comment]
Any update on this? Does it work for you as admin?

**Comment by readyact** [comment]
Now the installation works well, but as I search in the cortana or form the start menu and click the "search suggestions" based on my typing, I can only get the bing search result in IE. I have tried several browser and search engines from the installation folder setup.exe, but it still gives the same results.

**Comment by spikespaz** [comment]
🤔



Thanks,
Jacob Birkett<https://link.getmailspring.com/link/1537491700.local-c6f46e45-3f40-v1.4.2-f587b7b7@getmailspring.com/0?redirect=https%3A%2F%2Fspikespaz.com&recipient=cmVwbHkrMDBiZWM3Y2NjMGZkNmQ3YmZkMGM0OGVhNWMyZGE2MmZlMDI3ZTNmMjU3NDczNTFjOTJjZjAwMDAwMDAxMTdiYzA0NjY5MmExNjljZTE1OTczYmZiQHJlcGx5LmdpdGh1Yi5jb20%3D>

On Sep 20 2018, at 5:59 pm, readyact <notifications@github.com> wrote:

Now the installation works well, but as I search in the cortana or form the start menu and click the "search suggestions" based on my typing, I can only get the bing search result in IE. I have tried several browser and search engines from the installation folder setup.exe, but it still gives the same results.

**Comment by spikespaz** [comment]
🤔



Thanks,
Jacob Birkett<https://link.getmailspring.com/link/1537491700.local-c6f46e45-3f40-v1.4.2-f587b7b7@getmailspring.com/0?redirect=https%3A%2F%2Fspikespaz.com&recipient=Y29tbWVudEBub3JlcGx5LmdpdGh1Yi5jb20%3D>

On Sep 20 2018, at 5:59 pm, readyact <notifications@github.com> wrote:

Now the installation works well, but as I search in the cortana or form the start menu and click the "search suggestions" based on my typing, I can only get the bing search result in IE. I have tried several browser and search engines from the installation folder setup.exe, but it still gives the same results.

**Comment by spikespaz** [comment]
🤔



Thanks,
Jacob Birkett<https://link.getmailspring.com/link/1537491700.local-c6f46e45-3f40-v1.4.2-f587b7b7@getmailspring.com/0?redirect=https%3A%2F%2Fspikespaz.com&recipient=c2VhcmNoLWRlZmxlY3RvckBub3JlcGx5LmdpdGh1Yi5jb20%3D>

On Sep 20 2018, at 5:59 pm, readyact <notifications@github.com> wrote:

Now the installation works well, but as I search in the cortana or form the start menu and click the "search suggestions" based on my typing, I can only get the bing search result in IE. I have tried several browser and search engines from the installation folder setup.exe, but it still gives the same results.

**Comment by spikespaz** [comment]
Uninstall and reinstall?

**Comment by spikespaz** [comment]
This program is _only_ supposed to work for Windows 10 so I am at a loss. Was it working before? Go into your registry and delete the following registry items.

```
HKEY_CURRENT_USER\Software\Clients\SearchDeflector
HKEY_LOCAL_MACHINE\Software\Clients\SearchDeflector
HKEY_LOCAL_MACHINE\Software\RegisteredApplications\SearchDeflector (Value)
HKEY_CLASSES_ROOT\SearchDeflector
```

Delete the files in `C:/Program Files (x86)/Search Deflector` _after_ uninstalling from the Windows 10 apps list.

Then reinstall.
