### ISSUE TITLE
Missing support for CN Bing deflection

### ISSUE THREAD

**Issue by HueLiu** [spikespaz/search-deflector#32]
Hi. I'm here to give you a little feedback on bug.

My system version is Windows 10 RS5 Pro. 

Regions and languages are set to China.

1. My `setup.exe` settings:
![default](https://user-images.githubusercontent.com/19755727/46566662-6e049f80-c955-11e8-8a31-53ec9cbd8307.png)

2. When I search
![default](https://user-images.githubusercontent.com/19755727/46566650-30a01200-c955-11e8-9f9f-d090b67cb996.png)

3. The result
![default](https://user-images.githubusercontent.com/19755727/46566658-54fbee80-c955-11e8-97c2-0d7326c11f46.png)

**Cortana's default search engine is` cn.bing.com` instead of `www.bing.com`,**

I don't know if this is the reason why the default search engine can not be properly modified.

**Comment by HueLiu** [comment]
The browser can start normally, but the search engine is wrong. Thanks~

**Comment by HueLiu** [comment]
Excellent!  Everything is back to normal!

Now Bing can normally switch to Google search engine.

Thanks :)

**Comment by spikespaz** [comment]
Fixed in [release 0.2.3](https://github.com/spikespaz/search-deflector/releases/tag/0.2.3). The update should be available for you in about 6 hours, or you can run "Force Update" in the start menu folder. This has no difference from the build I sent you except for the version name.
