### ISSUE TITLE
Unable to launch installer Windows Defender SmartScreen

### ISSUE THREAD

**Issue by MaizeStarch** [spikespaz/search-deflector#33]
Hi, when I launch the installer, a message appears with the following title: "Windows protected your PC" and then triggers the previous problems.
It may be related with these problems and it makes some sense.

![untitled](https://user-images.githubusercontent.com/20288677/46567294-44685b80-c8f6-11e8-9c05-73ae2b7cfcd1.png)

Doesn't even work on older versions of Windows 10 (Tested)

Microsoft probably doesn't want the application to work marking it as a virus and inaviliting all its functionalities.

I mean, if Microsoft is able to place a Microsoft Edge ad to avoid installing Chrome or Firefox, imagine what it could do with any other program that it considers a potential danger in its products or services.

You should be in contact with Microsoft to possibly clarify doubts

**Comment by GhostofGoes** [comment]
@spikespaz I think the only way around this is by signing your release binaries

**Comment by spikespaz** [comment]
@GhostofGoes Yes, and I can't pay that much money for a cert until people start donating enough to support this stuff.

@MaizeStarch This is already addressed. You should read the [readme](https://github.com/spikespaz/search-deflector#i-found-a-bug--it-doesnt-work) before asking for help.

**Comment by MaizeStarch** [comment]
@spikespaz It looks like I'm not going to install useless Software with a poor Readme file.

I definitely don't recommend it.

**Comment by spikespaz** [comment]
@MaizeStarch I don't understand how you think [this](https://github.com/spikespaz/search-deflector/wiki/Troubleshooting) is poor.

Any suggestions?
