### ISSUE TITLE
Failed to spawn new process

### ISSUE THREAD

**Issue by panyuz** [spikespaz/search-deflector#34]
I have encountered an error launching Search Deflector.
The error information follows below.

**File:** `std\process.d`

**Line:** 752

**Message:**
```
Failed to spawn new process (无法成功完成操作，因为文件包含病毒或潜在的垃圾软件。)
```

**Stack Trace:**
```
0x011BA3EF
0x011BA1A2
0x011B327D

```

**Comment by spikespaz** [comment]
Would you mind translating that string for me? I can't read it.

**Comment by spikespaz** [comment]
I'm closing this issue because OP did not respond for 15 days.
