### ISSUE TITLE
Search Deflector launch failed

### ISSUE THREAD

**Issue by trongtunguyen08** [spikespaz/search-deflector#35]
I have encountered an error launching Search Deflector.
The error information follows below.

**File:** `std\windows\registry.d`

**Line:** 495

**Message:**
```
Value cannot be opened: "": The system cannot find the file specified. (error 2)
```

**Stack Trace:**
```
0x00085ECF
0x00085C82
0x0007ED5D

```

**Comment by spikespaz** [comment]
Duplicate of #8.
