### ISSUE TITLE
Command prompt window launches during search

### ISSUE THREAD

**Issue by maxloh** [spikespaz/search-deflector#36]
This situation happens after I updated to 0.3.2.
Reinstalling search-deflector does not solve the bug.
![screenshot 5703](https://user-images.githubusercontent.com/35831069/47263138-0aba6600-d52e-11e8-9ff8-c11b7127bae5.png)

**Comment by spikespaz** [comment]
I noticed this bug myself but thought it was just my system. Looking at the deprecated code again, I know exactly where the issue lies. Does it at least launch your browser with your search properly?

**Comment by maxloh** [comment]
Yes. The search is completed as it supposed to be and the black window closes automatically 0.5 second after it shows up.

**Comment by spikespaz** [comment]
Please confirm that this new version works.

https://ufile.io/58izb

The download will expire in one day. You should leave all installation options default.

**Comment by maxloh** [comment]
The new version works for me. No command prompt window launches during search.

**Comment by spikespaz** [comment]
Thanks. I'll release it.
