### ISSUE TITLE
Appx file won't install (missing certificate)

### ISSUE THREAD

**Issue by blackcomb-dev** [spikespaz/search-deflector#40]
When I try to sideload the 0.3.5 .appx file provided, Windows aborts the installation because of an untrusted certificate (see here:)
![image](https://user-images.githubusercontent.com/30536280/48374423-acd6f500-e679-11e8-9f63-6cbc63402aa4.png). This is with all previous copies uninstalled and Windows developer mode enabled on Skip Ahead build 18277.

**Comment by spikespaz** [comment]
Unpack it and debug load it yourself for now, or sign it with your own certificate. I don't know exactly how to get a certificate that isn't $199.95/year.

**Comment by blackcomb-dev** [comment]
Alrighty, thanks. Is the 0.3.5 update live in the Microsoft Store?

**Comment by spikespaz** [comment]
![image](https://user-images.githubusercontent.com/12502988/48374931-769e7300-e683-11e8-9c57-6f3639e5a88f.png)

Not quite. It's pretty slow.

**Comment by blackcomb-dev** [comment]
Alrighty, thanks for the update!

**Comment by GhostofGoes** [comment]
@spikespaz FYI: https://www.certum.eu/en/cert_offer_en_open_source_cs/

Looks like ~$29 for a cert, plus a $50 initial cost to get their crypto hardware.

**Comment by spikespaz** [comment]
@GhostofGoes I'm poor as hell.

**Comment by GhostofGoes** [comment]
Sorry 🙁 
Just a suggestion that's a little more reasonable than $200/yr the typical ones go for.
