### ISSUE TITLE
Not working for preview search

### ISSUE THREAD

**Issue by xpt1x** [spikespaz/search-deflector#41]
Works correctly for normal searches and opens up on preferred browser but still using BING for fast Preview search 😞 
**Any fix** ?

Screen Shot:

![searc](https://user-images.githubusercontent.com/33655587/48456018-70270d00-e7e3-11e8-917e-980e56a8d404.jpg)

**Comment by spikespaz** [comment]
This is addressed on the Troubleshooting page of the wiki, it cannot be fixed.

https://github.com/spikespaz/search-deflector/wiki/Troubleshooting#still-using-bing-in-the-search-ui
