### ISSUE TITLE
Can't install search deflector - win10 pro 1803 - 173134.407

### ISSUE THREAD

**Issue by buffondavid** [spikespaz/search-deflector#43]
I have encountered an error launching Search Deflector. I can't install it.
The error information follows below.

**File:** `std\windows\registry.d`

**Line:** 510

**Message:**
```
Failed to open requested key: "SOFTWARE\Clients\StartMenuInternet": Impossibile trovare il file specificato. (error 2)
```

**Stack Trace:**
```
0x001C342F
0x001C31E2
0x001BB2ED

```

**Comment by spikespaz** [comment]
This is a duplicate. Please see my reply to issue #42, and try the installer that I uploaded in my reply.
