### ISSUE TITLE
mouse gestures

### ISSUE THREAD

**Issue by Fink-MFG** [spikespaz/search-deflector#44]
I have encountered an error launching Search Deflector.
The error information follows below.

**File:** `std\windows\registry.d`

**Line:** 495

**Message:**
```
Value cannot be opened: "BrowserName": Sistem belirtilen dosyayı bulamıyor. (error 2)
```

**Stack Trace:**
```
0x00007FF71C66BB3D
0x00007FF71C66B896
0x00007FF71C66474C
0x00007FF71C65156C
0x00007FF71C62F3FA
0x00007FF71C631248
0x00007FF71C6219D2
0x00007FF71C62150D
0x00007FF71C621364
0x00007FF71C65777D
0x00007FF71C65762A
0x00007FF71C6760C0
0x00007FFF06F43034 in BaseThreadInitThunk
0x00007FFF08533691 in RtlUserThreadStart

```

**Comment by spikespaz** [comment]
What version of Windows 10 do you have installed? What architecture? Are you using the latest version of this software? What did just you do before SD crashed?

**Comment by spikespaz** [comment]
And what's up with the title?

**Comment by spikespaz** [comment]
Closing because OP has not responded. Please add additional information and I will reopen this issue.
