### ISSUE TITLE
Out of System Resources

### ISSUE THREAD

**Issue by harrypnyce** [spikespaz/search-deflector#48]
While trying to update Search Deflector on my laptop, I'm immediately presented with an `Out of system resources.` message:
![searchdeflector-systemresources](https://user-images.githubusercontent.com/32494212/53586026-4953d300-3b55-11e9-9227-51e9be197928.PNG)

And then again when completing the installation, I'm again presented with an identical error message:
![searchdeflector-complete](https://user-images.githubusercontent.com/32494212/53586070-612b5700-3b55-11e9-8681-0bb743b5af51.PNG)

Hardware & Software involved:
**HP Spectre-x360** laptop _(i7-8550U, 16GB RAM, 512GB NVMe SSD)_
- Windows 10 Professional
- Version: 1809
- OS build: 17763.316

No special steps required to reproduce, simply downloaded v1.0 Search Deflector and double-clicked to run, the messages appeared at each aforementioned event.  I tried to completely remove the software, then reboot and reinstall, yet I was faced with the same error issues.  Will attempt to install v1.0 again on a desktop PC later today when I get a chance.  Thank you for the wonderful software.

**Comment by harrypnyce** [comment]
If there's any log files, or any further information I can provide in an effort to troubleshoot this issue, please just say the word.  Setup appeared to complete, despite the issues.  Chose Brave browser as my default, as well as DuckDuckGo as my preferred search provider.

**Comment by spikespaz** [comment]
This error occurs (presumably) when the setup fails to load the image on the left for some reason. I think it's an issue with Inno Setup, and I don't know what to do about it. Also, did you disable the automatic updater when installing it? Because if you left it default, it should update in the background without a GUI

**Comment by spikespaz** [comment]
Is there a chance you aren't running this as an Administrator?

Try the one I upload
[SearchDeflector-Installer.zip](https://github.com/spikespaz/search-deflector/files/2969046/SearchDeflector-Installer.zip)
ed.

**Comment by spikespaz** [comment]
@harrypnyce Did you have the chance to test the one I sent you? If nobody gives more information I'll have to mark this one `inactive`.

**Comment by peatrick** [comment]
Sorry for leaving this one hanging. It may have had something to do with me changing default browser, I dunno. Version 1.0 is working wonderfully across three different Win10 (1809) machines I have, all using latest version of Brave browser.

Thank you for the incredible support and amazing piece of software. I hope it'll continue to work with forthcoming 1903 update.

This issue can be considered resolved, and marked closed. You're nice!

**Comment by harrypnyce** [comment]
Sorry for leaving this one hanging. It may have had something to do with me changing default browser, I dunno. Version 1.0 is working wonderfully across three different Win10 (1809) machines I have, all using latest version of Brave browser.

Thank you for the incredible support and amazing piece of software. I hope it'll continue to work with forthcoming 1903 update.

This issue can be considered resolved, and marked closed. You're nice!

**Comment by spikespaz** [comment]
Thanks for the update! FYI, I doubt that changing browser defaults would affect the installation of the software. Nevertheless, glad to hear it's working fine for you!

I'm going to mark this one as `wontfix` because it's an unresolved error without explanation. If it comes up again this can be reopened.

**Comment by spikespaz** [comment]
Please see the workaround I've added to the wiki [here](https://github.com/spikespaz/search-deflector/wiki/Troubleshooting#installer-crashes-with-out-of-system-resources-error) if you come across this issue and are looking for a solution.

**Comment by NicGom** [comment]
I do have this issue, tested on 2 computers, with built installer or with hiting the run button from inno setup.
It is relatively unsteady though, can stick for 5 consecutive attempts or work right away and several times in a row.
It may be related to the installer not releasing the image resource appropriately, not sure
