### ISSUE TITLE
Windows Search UI remains showing results from Bing?

### ISSUE THREAD

**Issue by Gerr1dan** [spikespaz/search-deflector#49]
Using the latest Chromium Edge Canary version, redirect to this browser works without any issue.
But it still searches with Bing as it's engine.

Furthermore, tried to see if changing the browser of choice worked, by reinstalling it and setting Firefox as it's browser, and it still redirects me too Edge Canary (might be Microsofts doing, with the Chromium shift) and of course still Bing.

Btw thanks for the effort you've put in this program so far!

**Comment by spikespaz** [comment]
Would you mind including your Windows version and other build information? I'm going to assume that you're using the latest Search Deflector version, but are you using Windows Insider Preview and what ring? This is symptom of MS changing the way Cortana URIs are constructed and I fear breaking changes may be coming in the future.

**Comment by Gerr1dan** [comment]
It's Win 10 Pro (64bit), version 1903 and the OS build is 18362.239. Not using the Insider preview builds.

**Comment by spikespaz** [comment]
Are you using the Windows Sore version or the classic version from releases?

If you're using the classic, uninstall it and try the UWP version.

https://www.microsoft.com/store/productId/9P8ZJJ80RZ2K
`WCPWD-MVRFG-D9MYJ-J2CFW-2CXCZ`

**Comment by saltukkos** [comment]
I can confirm, that browser opens with google, as i configured, but in-pane search shows bing results 
![image](https://user-images.githubusercontent.com/13440397/63640841-6403a080-c6cf-11e9-9063-537cad4ed8ab.png)
I use windows 10 pro 1903

**Comment by saltukkos** [comment]
Okay, this is designed behaviour as written in wiki :(

**Comment by spikespaz** [comment]
Ah. Every time someone asks this question I make the assumption that they mean that the search results opened in their browser are still from Bing, because I forget that the results in the start menu are Bing's and that people don't read the wiki. I'm going to make issue templates now.
