### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ExpertContributor** [spikespaz/search-deflector#50]
I have encountered an error launching Search Deflector.
The error information follows below.

**File:** `source\deflector.d`

**Line:** 34

**Message:**
```
Expected one URI argument, recieved: 
["E:\\Search Deflector\\deflector.exe"]
```

**Stack Trace:**
```
null
```

**Comment by spikespaz** [comment]
Strange, but this seems like a fluke. If it happens again let me know here and I'll reopen the issue.
