### ISSUE TITLE
Drop down selection only shows four items in the list

### ISSUE THREAD

**Issue by oscardobsonbrown** [spikespaz/search-deflector#52]
I want to use ecosia because "save the trees" but there isn't an option to do so, and the box with the custom search engine URL is greyed out.

**Comment by spikespaz** [comment]
Use the arrow keys when the combo box is focused. You can cycle through all options. Currently minigui doesn't show the scrollbar on the drop-down list.

**Comment by oscardobsonbrown** [comment]
That fixed it, Thank you.

**Comment by spikespaz** [comment]
It's not fixed. This is still a bug, just one I can't fix at the moment. I have to wait for @adamdruppe to fix minigui's `DropDownSelection` widget or put in the time and effort to do it myself. There are so many things on my project backlog that for now I guess this is just an issue that's going to have to be dealt with, it doesn't impair functionality so much.

**Comment by adamdruppe** [comment]
try the new minigui version now
