### ISSUE TITLE
Failed to open requested key: "shell\open\command"

### ISSUE THREAD

**Issue by andyruabon91** [spikespaz/search-deflector#62]
## Bug Description

If you have any other details, replace this line, otherwise delete it.

**File:** `std\windows\registry.d`

**Line:** 510

**Message:**

```
Failed to open requested key: "shell\open\command": The system cannot find the file specified. (error 2)
```

**Custom search engine URL:**
```
google.com/search?q={{query}}
```

| Windows Version | `1909` |
| --- | --- |
| Build Number | `18363` |
| Edition | `Enterprise` |
| Insiders Preview | No |

**Comment by spikespaz** [comment]
Please attempt a clean install by using the script to remove registry keys found [here](https://github.com/spikespaz/search-deflector/wiki/Troubleshooting#fresh--clean-reinstall) and then run the installer again. Let me know if the issue persists and I can assist you with this system-specific problem.
