### ISSUE TITLE
Search Deflector launch failed.

### ISSUE THREAD

**Issue by feng20190** [spikespaz/search-deflector#66]
![Snipaste_2020-06-05_17-56-11](https://user-images.githubusercontent.com/53474334/83863427-e5578b80-a755-11ea-8795-4c9d01f3c3a3.png)

**Comment by who-2000** [comment]
You're the same with me.Do you install it on the windows10 pro?

**Comment by spikespaz** [comment]
Please re-submit this issue the next time this message rears it's ugly head. Click "Yes" and it will fill out an issue template with appropriate details that are necessary to diagnose this problem. Please fill out the example and blank sections with any relevant information you can provide. Thanks.
