### ISSUE TITLE
Using Chrome with the certain user profile

### ISSUE THREAD

**Issue by salmivas** [spikespaz/search-deflector#67]
Good day!

Is it possible to implement a feature of using Chrome with the certain user profile? I use a bunch of profiles simultaneously and want to search using only the certain profile of Chrome. For now  SearchDeflecotr's logic is to open a last used window for searching.

**Comment by spikespaz** [comment]
I like this idea. Working on it now, coming in the next version. Thanks for the suggestion!

**Comment by spikespaz** [comment]
Sorry it's taking a while. I finished the feature but launching the browser with the extra arguments throws an error and I can't figure out why 🤔 and then life got in the way. Soon™

**Comment by salmivas** [comment]
No need to hurry. SearchDeflector is still the best and still have not competitors on the horizon. So will wait for the feature as long as it takes. 😊

**Comment by spikespaz** [comment]
Update coming tomorrow, bugs or not. Probably will need to release an update to patch more issues, but tomorrow nevertheless. Promise. Not sure how late but before my system clock hits midnight for sure. Sorry for the wait.

**Comment by spikespaz** [comment]
Implemented and closed in the latest release, 1.2.0. If you have any other specific feedback, requests, or suggestions relating to this feature, do not re-open this issue but please do feel free to comment. Thanks!

**Comment by salmivas** [comment]
Thank you, Jacob!
