### ISSUE TITLE
Invalid issue (original title: "我遇到了问题")

### ISSUE THREAD

**Issue by CooperZhuang** [spikespaz/search-deflector#68]
> **IMPORTANT:** READ EVERYTHING!!! That includes the wiki. Make sure you've skimmed the wiki before making a bug report.
> https://github.com/spikespaz/search-deflector/wiki
>
> This issue should be properly formatted in markdown. If you don't know what that is, read the following website before continuing:
> https://guides.github.com/features/mastering-markdown/
>
> Most of the text in this issue should be replaced with your own or deleted. Do not delete section headers unless the information they would contain is irrelevant or inapplicable.

## Bug Description

If you have any other details, replace this line, otherwise delete it.

**File:** `std\windows\registry.d`

**Line:** 510

**Message:**

```
Failed to open requested key: "SOFTWARE\Classes\CentHTM.GRGFIWRJJWWB4NWQRGE6UCVGEA\shell\open\command": 系统找不到指定的文件。 (error 2)
```

## How to Reproduce

**Query string:**
```

```

**Query or URL:**
```

```

**Steps to reproduce the behavior:**

## Environmental Details

**Browser**: 

**Search Engine:** 

**Custom browser path:**
```

```

**Custom search engine URL:**
```
google.com/search?q={{query}}
```

| Windows Version | `2004` |
| --- | --- |
| Build Number | `19041` |
| Edition | `Enterprise` |
| Insiders Preview |  |

**Comment by spikespaz** [comment]
Issue reports are expected to be in English as I am a developer who reads, writes and speaks English. You did not make any attempt to provide *any* of the information requested by the template. Closing and done.
