### ISSUE TITLE
Windows search not working after installation

### ISSUE THREAD

**Issue by meviuswg** [spikespaz/search-deflector#69]
## Bug Description

**File:** `std\process.d`

**Line:** 1275

**Message:**

```
Failed to spawn new process (The parameter is incorrect.)
```

## Environmental Details

**Browser**: 

**Search Engine:** 

**Custom browser path:**
```
C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
```

**Custom search engine URL:**
```
google.com/search?q={{query}}
```

| Windows Version | `1909` |
| --- | --- |
| Build Number | `18363` |
| Edition | `EnterpriseN` |
| Insiders Preview |  |

**Comment by spikespaz** [comment]
Do you remember what you searched for from the taskbar?

**Comment by spikespaz** [comment]
It looks like you specified a custom browser path instead of selecting from the recognized browsers that are installed as HTTPS/HTTP protocol handlers. Is there  a reason for this? Are you sure that the path is correct? I see that in the automated report the *Browser* field is not populated.

**Comment by mrBrain101** [comment]
Had the same problem. 
Prerequisite is having Chrome as a default windows browser.
Steps to repeat: choose Chrome from the list of browsers in the configuration window with the C:\Program files.....etc. path.
Solution: open configure.exe and select "System default" in the browser list.

Thanks for the great feature!  Will buy or sponsor after checking it some more.

**Comment by spikespaz** [comment]
Both of you, please try this again with the newest 1.2.0 release and report back as I may have unintentionally fixed this issue. Thanks!

**Comment by mrBrain101** [comment]
spikespaz, works now properly when choosing Chrome and its path.
Thanks, man!
