### ISSUE TITLE
SearchDeflector could not deflect the URI / launch failed

### ISSUE THREAD

**Issue by mages66** [spikespaz/search-deflector#70]
> **IMPORTANT:** READ EVERYTHING!!! That includes the wiki. Make sure you've skimmed the wiki before making a bug report.
> https://github.com/spikespaz/search-deflector/wiki
>
> This issue should be properly formatted in markdown. If you don't know what that is, read the following website before continuing:
> https://guides.github.com/features/mastering-markdown/
>
> Most of the text in this issue should be replaced with your own or deleted. Do not delete section headers unless the information they would contain is irrelevant or inapplicable.

## Bug Description

If you have any other details, replace this line, otherwise delete it.

**File:** `std\process.d`

**Line:** 1275

**Message:**

```
Failed to spawn new process (Parametro non corretto.)
```

## How to Reproduce

**Query string:**
```

```

**Query or URL:**
```

```

**Steps to reproduce the behavior:**

1. Click on Windows search button on windows toolbar
2. Write any internet question
3. Click on any web result search (i.e. not pc apps/functions)

## Expected Behavior

They open 2 consequent dialog boxes
1. SearchDeflector could not deflect the URI to your browser...
2. SearchDeflector launch failed.... report...

## Environmental Details

**Browser**: Firefox 77.0.1 (64 bit)

**Search Engine:** Google

**Custom browser path:**
```
C:\Program Files\Mozilla Firefox\firefox.exe
```

**Custom search engine URL:**
```
google.com/search?q={{query}}
```

| Windows Version | `1909` |
| --- | --- |
| Build Number | `18363` |
| Edition | `Enterprise` |
| Insiders Preview |  |

**Comment by spikespaz** [comment]
Not enough information provided to determine a cause.
