### ISSUE TITLE
Windows help link can't open

### ISSUE THREAD

**Issue by chsbuffer** [spikespaz/search-deflector#77]
## Bug Description

Can't Open Windows Help link

## How to Reproduce

![animation gif1](https://user-images.githubusercontent.com/33744752/87388488-7e8c8400-c5d7-11ea-93ac-db3a4eda6c0d.gif)

**Browser**: System Default

**Search Engine:** Google

**Steps to reproduce the behavior:**

1. Go to 'Explorer'
2. Click on 'help icon'
3. See error

or

1. Press Win+F1

## Expected Behavior

Browser opened the windows help page

## Environmental Details

| Windows Version | `2004` |
| --- | --- |
| Build Number | `19041.329` |
| Insiders Preview | no|

**Comment by spikespaz** [comment]
Thanks for reporting. Fix will be released with the next version.
