### ISSUE TITLE
search-deflector crushed suddenly while I am using File Explorer

### ISSUE THREAD

**Issue by max-hk** [spikespaz/search-deflector#79]
> **IMPORTANT:** READ EVERYTHING!!! That includes the wiki. Make sure you've skimmed the wiki before making a bug report.
> https://github.com/spikespaz/search-deflector/wiki
>
> This issue should be properly formatted in markdown. If you don't know what that is, read the following website before continuing:
> https://guides.github.com/features/mastering-markdown/
>
> Most of the text in this issue should be replaced with your own or deleted. Do not delete section headers unless the information they would contain is irrelevant or inapplicable.

## Bug Description

If you have any other details, replace this line, otherwise delete it.

**File:** `source\deflector.d`

**Line:** 53

**Message:**

```
There was an error deflecting your search. Passed URI is:	microsoft-edge:https://go.microsoft.com/fwlink/?LinkId=528884
```

## How to Reproduce

**Query string:**
```

```

**Query or URL:**
```

```

**Steps to reproduce the behavior:**

I don't know. I didn't even open start menu/Windows search at all.

## Environmental Details

**Browser**: UNKNOWN STRING

**Search Engine:** UNKNOWN STRING

**Custom browser path:**
```

```

**Custom search engine URL:**
```
google.com/search?q={{query}}
```

| Windows Version | `2004` |
| --- | --- |
| Build Number | `19041` |
| Edition | `Core` |
| Insiders Preview |  |

**Comment by spikespaz** [comment]
This is fixed by 49e833f6eae382acd872889709954d28ca441b90.
