### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by caralu74** [spikespaz/search-deflector#82]
I can help translate into Spanish. Are you interested?

**Comment by spikespaz** [comment]
Yes please, I would greatly appreciate this.

To get started, please create a fork of the `dev` branch and add your name to the [translators list](https://github.com/spikespaz/search-deflector/tree/dev#translations) in the README, for the language code you create.

Copy [lang/en-US.txt](https://github.com/spikespaz/search-deflector/blob/dev/lang/en-US.txt) and change all of the values to what is appropriate for your translation. Name the file as your language code, for example `es-ES.txt`, commit your translation, and submit a pull-request.

Thank you!

**Comment by caralu74** [comment]
Warm greetings!
I want to be practical and fast
So I will just attach the file.
Yours sincerely: Carlos Luna.
// All English US translations for the configuration user interface.

// Page and window titles
title.window:               Configure Search Deflector
title.settings_page:        Opciones
title.language_page:        Idioma
title.update_page:          Actualizar

// Text fragments used in labels
//// Settings page
fragment.version:           Versión
fragment.author:            Autor
//// Update page
fragment.current_version:   Versión actual
fragment.build_date:        Fecha de construcción
fragment.latest_version:    última versión
fragment.uploader:          Encargado
fragment.timestamp:         Registro de tiempo
fragment.binary_size:       Tamaño binario
fragment.download_count:    Tiempo de descarga

// Labels used for input fields and options
//// Settings page
label.browser_name:         Navegador preferido
label.browser_path:         Ejecutable del navegador
label.engine_name:          Buscador preferido
label.engine_url:           URL del buscador preferido
label.profile_dir:          Perfil de usuario en Chrome/Firefox
label.enable_profile:       Habilitar
//// Language page
label.language_select:      Idioma de la interfaz

// Static options in dropdown menus or radio button groups
//// Settings page
option.custom_browser:      Personalizar
option.default_browser:     Predeterminado del sistema
option.custom_engine:       Personalizar
//// Language page
option.default_language:    Predeterminado del sistema

// Button label text
//// Settings page
button.apply:               Aplicar
button.website:             Sitio Web
button.close:               Cerrar
//// Update page
button.update:              Actualizar
button.details:             Detalles

**Comment by spikespaz** [comment]
Merged in commit 385969d247c62823827d959f49a78d74852dabd1.

**Comment by caralu74** [comment]
How can I know if there is new untranslated lines?
Do not forget that if you need any translation help I'm here, ready to help.
