### ISSUE TITLE
Search menu disappears when you start typing.

### ISSUE THREAD

**Issue by pdhixenbaugh** [spikespaz/search-deflector#84]
1. Press Windows key
2. Start Menu appears
3. Start typing

>> expect search to start looking for what you're typing.
>> Instead, search window closes, and you type into whatever was underneath.

If I try steps 1-3 a few times, eventually, search won't disappear and I can search for something, e.g. an app to launch.

Wonder what's going on...

**Comment by spikespaz** [comment]
This is a Microsoft bug. Reboot your computer.
